---
- name: Check House
  hosts: localhost
  become: true
  tasks:
    - name: Verifie les maisons
      ansible.builtin.file:
        state: directory
        path: "{{ village_full_path }}/{{ item }}_maison"
        owner: "{{ item }}"
        group: "{{ item }}"
      loop: "{{ current_character }}"