---
- name: Check House
  hosts: localhost
  tasks:
    - name: Verifie les maisons
      ansible.builtin.file:
        state: directory
        path: "{{ village_full_path }}/{{ item }}_maison"
      loop: "{{ current_character }}"